/**
 * BEST HACK 2020 (web)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The Body1 model module.
* @module model/Body1
* @version 0.0.3
*/
export default class Body1 {
    /**
    * Constructs a new <code>Body1</code>.
    * @alias module:model/Body1
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body1} obj Optional instance to populate.
    * @return {module:model/Body1} The populated <code>Body1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body1();
                        
            
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} login
    */
    login = undefined;
    /**
    * @member {String} password
    */
    password = undefined;




}
