/**
 * BEST HACK 2020 (web)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The Body2 model module.
* @module model/Body2
* @version 0.0.3
*/
export default class Body2 {
    /**
    * Constructs a new <code>Body2</code>.
    * @alias module:model/Body2
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body2</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body2} obj Optional instance to populate.
    * @return {module:model/Body2} The populated <code>Body2</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body2();
                        
            
            if (data.hasOwnProperty('rights')) {
                obj['rights'] = ApiClient.convertToType(data['rights'], 'String');
            }
            if (data.hasOwnProperty('blocked')) {
                obj['blocked'] = ApiClient.convertToType(data['blocked'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} rights
    */
    rights = undefined;
    /**
    * @member {Boolean} blocked
    */
    blocked = undefined;




}
