/**
 * BEST HACK 2020 (web)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The OneOfinlineResponse200 model module.
* @module model/OneOfinlineResponse200
* @version 0.0.3
*/
export default class OneOfinlineResponse200 {
    /**
    * Constructs a new <code>OneOfinlineResponse200</code>.
    * @alias module:model/OneOfinlineResponse200
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OneOfinlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfinlineResponse200} obj Optional instance to populate.
    * @return {module:model/OneOfinlineResponse200} The populated <code>OneOfinlineResponse200</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfinlineResponse200();
                        
            
        }
        return obj;
    }





}
